# Multi-Factor IDS Configuration for Windows

# Global settings
global:
  log_level: INFO
  data_retention_days: 90
  timezone: UTC

# Network monitoring
network:
  interfaces:
    # Use actual Windows interface names from your system
    # Based on your log, pick one or more of these:
    - "\\Device\\NPF_{A9AC6786-50AA-42B0-9B9A-8A580A2E8299}" # Usually WiFi
    - "\\Device\\NPF_{C8CCE713-A713-42B2-8C4B-3CB746A73658}" # Usually main ethernet 
    # Or use friendly names if your network monitor supports them:
    # - "Ethernet"
    # - "Wi-Fi"
  capture_filter: ""
  promiscuous_mode: true
  packet_timeout: 60
  max_packets: 10000

# Host monitoring
host:
  monitor_processes: true
  monitor_files: true
  monitor_network: true
  scan_interval: 30
  watched_directories:
    # Windows system directories
    - "C:\\Windows\\System32"
    - "C:\\Windows\\SysWOW64"
    - "C:\\Program Files"
    - "C:\\Program Files (x86)"
    - "C:\\Users"
    - "C:\\ProgramData"
    - "C:\\Windows\\Temp"

# Baseline engine
baseline:
  learning_period_days: 7
  update_interval_hours: 24
  anomaly_threshold: 0.95
  features:
    - network_traffic
    - process_activity
    - file_access
    - user_behavior

# Correlation engine
correlation:
  time_window_minutes: 5
  max_events_per_window: 10000
  correlation_threshold: 0.8
  rules_file: config/correlation_rules.yaml

# Alerting
alerts:
  severity_levels:
    - LOW
    - MEDIUM
    - HIGH
    - CRITICAL
  notification_methods:
    - email
    - webhook
    - syslog
  email:
    smtp_server: smtp.gmail.com
    smtp_port: 465
    username: zero.business.hub@gmail.com
    password: llxv qyoy bjvu xflg
  webhook:
    url: http://your-webhook-url.com/alerts

# Database connections
databases:
  elasticsearch:
    host: localhost
    port: 9200
    index_prefix: ids
  redis:
    host: localhost
    port: 6379
    db: 0
  postgres:
    host: localhost
    port: 5432
    database: ids_db
    username: ids_user
    password: ids_password

# API settings
api:
  host: 0.0.0.0
  port: 5001  # Changed from 5000 to avoid conflict
  debug: false
  secret_key: your_secret_key_here

# Dashboard settings (if you add web dashboard later)
dashboard:
  host: 0.0.0.0
  port: 5000  # Keep dashboard on 5000, API on 5001
  refresh_interval_seconds: 10
  max_displayed_alerts: 100
  charts_history_hours: 24